package render_test

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/santhosh-tekuri/jsonschema/v6"
)

// docs/character.schema.json describes what this build writes, and CI is what
// keeps it honest. It is not a promise to records already written: the PRD
// rules out cross-version record compatibility, because a record is
// regenerable from its seed and nothing in it is hand-written.
//
// Every golden and both documented examples are validated here. A schema
// nothing validates is a description that drifts away from the thing it
// describes.
const (
	schemaPath = "../docs/character.schema.json"
	goldenDir  = "../chargen/testdata"
	docsDir    = "../docs"
)

func compileSchema(t *testing.T) *jsonschema.Schema {
	t.Helper()

	compiler := jsonschema.NewCompiler()

	text, err := os.ReadFile(schemaPath)
	if err != nil {
		t.Fatalf("reading the schema: %v", err)
	}

	doc, err := jsonschema.UnmarshalJSON(bytes.NewReader(text))
	if err != nil {
		t.Fatalf("the schema is not JSON: %v", err)
	}

	added := compiler.AddResource(schemaPath, doc)
	if added != nil {
		t.Fatalf("adding the schema: %v", added)
	}

	schema, err := compiler.Compile(schemaPath)
	if err != nil {
		t.Fatalf("the schema does not compile: %v", err)
	}

	return schema
}

func validate(t *testing.T, schema *jsonschema.Schema, path string) {
	t.Helper()

	text, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}

	var record any

	err = json.Unmarshal(text, &record)
	if err != nil {
		t.Fatalf("%s is not JSON: %v", path, err)
	}

	invalid := schema.Validate(record)
	if invalid != nil {
		t.Errorf("%s does not match the schema:\n%v", filepath.Base(path), invalid)
	}
}

// Every record this repository writes matches the schema that describes it.
func TestEveryGoldenMatchesTheSchema(t *testing.T) {
	t.Parallel()

	schema := compileSchema(t)

	records, err := filepath.Glob(filepath.Join(goldenDir, "*.json"))
	if err != nil {
		t.Fatalf("looking for goldens: %v", err)
	}

	if len(records) == 0 {
		t.Fatal("no goldens found; the schema would be validated against nothing")
	}

	for _, path := range records {
		validate(t, schema, path)
	}
}

// The two documented examples, which are generated by the same path that
// writes the goldens and so cannot drift from what the engine emits.
func TestTheDocumentedExamplesMatchTheSchema(t *testing.T) {
	t.Parallel()

	schema := compileSchema(t)

	for _, name := range []string{"character.minimal.json", "character.complete.json"} {
		validate(t, schema, filepath.Join(docsDir, name))
	}
}

// A record that does not say what shape it is does not validate.
//
// That is the whole of #76: v1.0.0 means a frozen and supported record (#74),
// and a promise needs something to promise about. `build` names the writer
// and is absent from anything generated in-process; `ruleset` names the source
// text. Neither says what the file looks like, so the schema requires a field
// that does - and this is what would notice if it stopped being written.
func TestARecordWithoutItsShapeDoesNotValidate(t *testing.T) {
	t.Parallel()

	schema := compileSchema(t)

	text, err := os.ReadFile(filepath.Join(docsDir, "character.minimal.json"))
	if err != nil {
		t.Fatalf("reading the minimal example: %v", err)
	}

	var body map[string]any

	err = json.Unmarshal(text, &body)
	if err != nil {
		t.Fatalf("the minimal example is not JSON: %v", err)
	}

	if _, named := body["record"]; !named {
		t.Fatal("the minimal example does not name its shape, so removing it proves nothing")
	}

	delete(body, "record")

	if schema.Validate(body) == nil {
		t.Error("a record with no shape validated; nothing holds the promise to anything")
	}
}
