package dice_test

import (
	"testing"

	"github.com/philoserf/ctchargen/dice"
)

// A die is 1 through 6. Nothing else is a die.
func TestDieStaysInRange(t *testing.T) {
	t.Parallel()

	s := dice.New(1)
	seen := [7]bool{}

	for i := range 6000 {
		got := s.Die()
		if got < 1 || got > 6 {
			t.Fatalf("draw %d: Die() = %d, want 1..6", i, got)
		}
		seen[got] = true
	}

	for face := 1; face <= 6; face++ {
		if !seen[face] {
			t.Errorf("face %d never appeared in 6000 draws; the die does not reach it", face)
		}
	}
}

// One seed means one stream. This is the whole of the determinism promise
// within a build.
func TestSeedReproducesTheStream(t *testing.T) {
	t.Parallel()

	for _, seed := range []uint64{0, 1, 42, 1 << 53, ^uint64(0)} {
		a, b := dice.New(seed), dice.New(seed)
		for i := range 100 {
			if x, y := a.Die(), b.Die(); x != y {
				t.Fatalf("seed %d, draw %d: %d != %d", seed, i, x, y)
			}
		}
	}
}

// The values themselves, pinned. A change here is a change to every seeded
// character ever generated by this tool, which is allowed but is never
// silent: it must be read in this diff before it is read in a golden.
func TestTheStreamIsThisStream(t *testing.T) {
	t.Parallel()

	want := map[uint64][]int{
		0:  {2, 5, 3, 3, 3, 1, 5, 3, 5, 6, 3, 2},
		1:  {6, 1, 6, 6, 2, 6, 5, 1, 4, 2, 3, 6},
		42: {4, 3, 4, 4, 6, 2, 2, 5, 5, 3, 1, 1},
	}

	for seed, expected := range want {
		s := dice.New(seed)
		for i, w := range expected {
			if got := s.Die(); got != w {
				t.Errorf("seed %d, draw %d: Die() = %d, want %d", seed, i, got, w)
			}
		}
	}
}

// A 2D throw is two dice from the same stream, first die then second — not
// one draw from a wider range, and not the two in the other order.
func TestTwoDiceIsTwoDiceInOrder(t *testing.T) {
	t.Parallel()

	const seed = 7

	byOnes := dice.New(seed)
	wantFirst, wantSecond := byOnes.Die(), byOnes.Die()

	byPair := dice.New(seed)
	first, second := byPair.TwoDice()

	if first != wantFirst || second != wantSecond {
		t.Errorf("TwoDice() = (%d, %d), want (%d, %d): a 2D throw must draw the same two dice, in the same order, as two Die calls",
			first, second, wantFirst, wantSecond)
	}
}

// A throw the procedure does not make consumes nothing, so the count of dice
// drawn is part of what a seed means.
func TestDrawnCountsEveryDie(t *testing.T) {
	t.Parallel()

	s := dice.New(1)
	if got := s.Drawn(); got != 0 {
		t.Fatalf("a fresh stream has Drawn() = %d, want 0", got)
	}

	s.Die()
	if got := s.Drawn(); got != 1 {
		t.Errorf("after one Die: Drawn() = %d, want 1", got)
	}

	s.TwoDice()
	if got := s.Drawn(); got != 3 {
		t.Errorf("after a 2D throw: Drawn() = %d, want 3; a 2D throw draws two dice", got)
	}
}

// Different seeds are different characters. A weak property, but it fails
// loudly if the seed ever stops reaching the generator.
func TestDistinctSeedsDiverge(t *testing.T) {
	t.Parallel()

	a, b := dice.New(1), dice.New(2)
	for range 40 {
		if a.Die() != b.Die() {
			return
		}
	}
	t.Error("seeds 1 and 2 produced 40 identical dice; the seed is not reaching the generator")
}
